[tools]
"aqua:astral-sh/uv" = "latest"
"aqua:starship/starship" = "latest"
"aqua:tree-sitter/tree-sitter" = "latest"
go = "1.26.2"
node = "lts"
"npm:@earendil-works/pi-coding-agent" = { version = "latest" }
rust = "stable"
"pipx:huggingface_hub" = "latest"
gh = "latest"
claude = "latest"
"cargo:forgejo-cli" = "latest"
"npm:context-mode" = "latest"
"pipx:spec-kitty-cli" = "latest"
bitwarden = "latest"
