update

upgrade

# Install basics
install grc
install coreutils
install spark

# Install Python
install python
install python3
install pyenv

# Install Ruby
install rbenv

# Install Java
install maven
install gradle
install grails

# SCM
install git
install hg

# Install OSX Apps

tap phinze/cask
install brew-cask
tap caskroom/versions

# ToDo: Add a cask for the JDK
cask install alfred
cask install arduino
cask install audio-hijack-pro
cask install bartender
cask install caffeine
cask install choosy
cask install dash
cask install dropbox
cask install fantastical
cask install firefox
cask install fluid
cask install flux
cask install induction
cask install intellij-idea-ce
cask install istat-menus
cask install iterm2
cask install google-chrome
cask install google-drive
cask install google-hangouts
cask install gpgtools
cask install graphsketcher
cask install keyboard-maestro
cask install mailmate
cask install marked
cask install node
cask install nvalt
cask install onepassword
cask install omnigraffle
cask install omnifocus
cask install omnioutliner
cask install omnipresence
cask install p4merge
cask install pandoc
cask install postgres
cask install pycharm-ce
cask install rdm
cask install robomongo
cask install screenflow
cask install scrivener
cask install sequel-pro
cask install spotify
cask install sublime-text3
cask install skype
cask install sourcetree
cask install textexpander
cask install transmit
cask install the-unarchiver
cask install utorrent
cask install vagrant
cask install virtualbox
cask install visualvm
cask install vlc
cask install vmware-fusion
cask install wireshark
cask install xquartz

cleanup
