update

upgrade

# Install basics
install grc
install coreutils
install spark

# Install Python
install python
install python3
install pyenv

# Install Ruby
install rbenv

# Install Java
install maven
install gradle

# Install OSX Apps

tap phinze/cask
install brew-cask

cask install alfred
cask install audio-hijack-pro
cask install bartender
# lightheadsw.com is 503'ing
# cask install caffeine
cask install choosy
cask install dash
cask install dropbox
cask install fantastical
cask install firefox
cask install fluid
cask install flux
cask install induction
cask install intellij-idea-community
cask install istat-menus
cask install iterm2
cask install google-chrome
cask install google-hangouts
cask install marked2
cask install node
cask install notational-velocity
cask install onepassword
cask install omnigraffle
cask install omnifocus
cask install omnigraphsketcher
cask install omnioutliner
cask install pandoc
cask install postgres-app
cask install pycharm-community
cask install redis-desktop-manager
cask install robomongo
cask install screenflow
cask install scrivener
cask install sequel-pro
cask install sublime-text
cask install skype
cask install sourcetree
cask install textexpander
cask install transmit
cask install the-unarchiver
cask install vagrant
cask install virtualbox
cask install visualvm
cask install vlc
cask install vmware-fusion
cask install wireshark
cask install xquartz

cleanup
