idle_bg = "#44475A"
idle_fg = "#F8F8F2"
info_bg = "#6272A4"
info_fg = "#F8F8F2"
good_bg = "#50FA7B"
good_fg = "#282A36"
warning_bg = "#FFB86C"
warning_fg = "#F8F8F2"
critical_bg = "#FF5555"
critical_fg = "#F8F8F2"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
