#aliases go here
# Vagrant
alias vgu='vagrant up'
alias vgd='vagrant destroy'
alias vgr='vagrant reload'
alias vgh='vagrant halt'
alias vgs='vagrant ssh'
alias vgst='vagrant status'
alias vgsu='vagrant suspend'
alias vgsh='vagrant share'
alias vgl='vagrant login'
alias vgp='vagrant provision'
alias vgi='vagrant init'
alias vgpi='vagrant plugin'
alias vgpkg='vagrant package'
alias vggs='vagrant global-status'
alias vgc='vagrant connect'
alias vgrdp='vagrant rdp'
alias dm='docker-machine'
alias dml='docker-machine ls'
alias dme='docker-machine env'
alias dmu='docker-machine start'
alias dms='docker-machine stop'
alias dmr='docker-machine rm'
alias dmsh='docker-machine ssh'
alias dmc='docker-machine create'
alias dcu='docker-compose up -d'
alias dcs='docker-compose stop'
alias dr='docker run'
alias dps='docker ps'
alias drit='docker run -it'
alias di='docker images'
alias did='docker images -f "dangling=true"'
alias drm='docker rm'
alias drmi='docker rmi'
