#aliases go here
# Vagrant
alias vgu='vagrant up'
alias vgd='vagrant destroy'
alias vgr='vagrant reload'
alias vgh='vagrant halt'
alias vgs='vagrant ssh'
alias vgst='vagrant status'
alias vgsu='vagrant suspend'
alias vgsh='vagrant share'
alias vgl='vagrant login'
alias vgp='vagrant provision'
alias vgi='vagrant init'
alias vgpi='vagrant plugin'
alias vgpkg='vagrant package'
alias vggs='vagrant global-status'
alias vgc='vagrant connect'
alias vgrdp='vagrant rdp'
